# Builds a basic Centos<%= $os_major %> container with pe-agent installed
# This image is for training purposes and is not intended for production environments.
FROM <%= $basename %>:<%= $os_major %>
MAINTAINER Josh Samuelson <js@puppetlabs.com>
ENV HOME /root/
ENV TERM xterm
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/puppetlabs/puppet/bin
ADD base_cache.repo /etc/yum.repos.d/base_cache.repo
ADD epel_cache.repo /etc/yum.repos.d/epel_cache.repo
ADD updates_cache.repo /etc/yum.repos.d/updates_cache.repo
ADD yum.conf /etc/yum.conf
RUN yum -y install  tar dmidecode which logrotate cyrus-sasl libxslt cronie pciutils git rubygems vim tree csh zsh net-tools wget redhat-logos
RUN gem install multipart-post -v 1.2.0
RUN rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-<%= $os_major %>.noarch.rpm
RUN yum -y install puppet-agent
ADD puppet.conf /etc/puppetlabs/puppet/puppet.conf
ADD download_catalogs.sh /usr/local/bin/download_catalogs.sh
ADD refresh-mcollective-metadata /usr/local/bin/refresh-mcollective-metadata
ADD root.cron /var/spool/cron/root
RUN chkconfig --add crond
