alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

if [ -f /etc/bashrc ]; then
  source /etc/bashrc
fi

# Colored bash prompt
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ '

# Sync bash history for quest status
export PROMPT_COMMAND='history -a; history -r'
